### ISSUE TITLE
Display Project and Type in dibAdmin

### ISSUE THREAD

**Issue by andre-webdev** [Dropinbase/Releases#14]
Request that an item be placed in the top-right corner of the dibAdmin container (7129) to clearly indicate the site that this relates to. If I have multiple dibDesigner tabs open and wish to copy configs from one to another, the sites are indistinguishable apart from the url.

I think that if there is a clear indication, For example "Project X Staging" in a large font, it will save developers time and possible embarrassment.

These values could be populated from the environment variables, for example : {{getEnv('dib_display')}}
![dibDesign Environment](https://user-images.githubusercontent.com/61619326/84510601-a2516700-acc5-11ea-876c-0ca3885e58db.PNG)

**Comment by dawie-git** [comment]
Add following to Environment.php:
`'admin_site_name' => 'xxxx xxxx',`
=> refresh your browser (/nav/dibAdmin) it should work.

**If Environment.php is in your repo that gets deployed to ALL servers (like with F&P), then rather do this:**
`'admin_site_name' => DIB::$ADMINSITENAME,`

And then add this to DibTmpl.php:
`public static $ADMINSITENAME = 'xxxx xxxx';`

Then delete your /runtime/Dib.php file so that it can be regenerated.
