### ISSUE TITLE
Can't clear either container crud or cache

### ISSUE THREAD

**Issue by dimavisser** [Dropinbase/Releases#32]
The error keeps coming up. Reloading the designer does not help. Clicking the red button is the only option which works now - but that clears the whole crud & cache and slows down the workflow a lot.

![image](https://user-images.githubusercontent.com/33894592/90665765-c93f9280-e24c-11ea-8ffe-63c56482adce.png)

**Comment by dawie-git** [comment]
Hi Dima. It seems this container is linked to a (module) dropin which is
listed in the said file (/runtime/inclduePermFiles.php).

Dropinbase treats files in dropins listed in this file as though you are
not their "owner". For eg. the containers created for Dropinbase's admin UI
is in setNgxMaterial/dibAdmin... you can't clear their cache or crud since
if you do, you won't be able to recreate them...

Perhaps you linked the container to the wrong module dropin or that file
has this container's dropin listed?




--
David Blake
http://www.dropinbase.com

**Comment by dimavisser** [comment]
@dawie-git I do not have a logical answer. 90% of the time any container's cache & crud can be simply cleared. It just backfires every now and again. Then if I clear via the red button, i can the very next moment clear crud/cache and it will work again. 

I did clear this container's cache & crud multiple times already and everything worked.

**Comment by dawie-git** [comment]
Okay, thanks Dima... I'll look into it.

--
David Blake
http://www.dropinbase.com

**Comment by cobuscoetsee** [comment]
Resolved
